name: flutter_studio_cli
description: CLI tool for Flutter Studio - Add beautiful UI components to your Flutter project
version: 0.3.0
repository: https://github.com/TejasS1233/flutter-studio/tree/main/flutter_studio_cli
homepage: https://github.com/TejasS1233/flutter-studio

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.4.0
  http: ^1.2.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  flutter_studio: flutter_studio_cli
